pages:
  stage: deploy
  script:
    - mkdir .public
    - cp football_schedule.html .public/index.html
  artifacts:
    paths:
      - .public
  only:
    - main  # or use 'master' depending on your branch name
